/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 04755678030
 */
public class ConversaoTemperatura extends javax.swing.JFrame {

    /**
     * Creates new form ConversaoTemperatura
     */
    public ConversaoTemperatura() {
        initComponents();
    }

    private static int celsiusParaKelvin(int tCelsius) {
        return tCelsius + 273;
    }

    private static int kelvinParaCelsius(int tKelvin) {
        return tKelvin - 273;
    }

    private static int fahrenheitParaCelsius(int tFahr) {
        double temp = (tFahr - 32.0) / 9 * 5;
        return (int) temp;
    }

    private static int celsiusParaFahrenheit(int tCelsius) {
        double temp = (tCelsius / 5) * 9 + 32;
        return (int) temp;
    }

    private static int kelvinParaFahrenheit(int tKelvin) {
        return celsiusParaFahrenheit(kelvinParaCelsius(tKelvin));
    }

    private static int fahrenheitParaKelvin(int tFahr) {
        return celsiusParaKelvin(fahrenheitParaCelsius(tFahr));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoOrigem = new javax.swing.ButtonGroup();
        grupoDestino = new javax.swing.ButtonGroup();
        sliOrigem = new javax.swing.JSlider();
        botReiniciar = new javax.swing.JButton();
        botSair = new javax.swing.JButton();
        pOrigem = new javax.swing.JPanel();
        rbCelsiusO = new javax.swing.JRadioButton();
        rbKelvinO = new javax.swing.JRadioButton();
        rbFahrO = new javax.swing.JRadioButton();
        pDestino = new javax.swing.JPanel();
        rbCelsiusD = new javax.swing.JRadioButton();
        rbKelvinD = new javax.swing.JRadioButton();
        rbFahrD = new javax.swing.JRadioButton();
        lConversao = new javax.swing.JLabel();
        lOrigem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sliOrigem.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        sliOrigem.setForeground(new java.awt.Color(51, 51, 51));
        sliOrigem.setMajorTickSpacing(10);
        sliOrigem.setMinorTickSpacing(2);
        sliOrigem.setOrientation(javax.swing.JSlider.VERTICAL);
        sliOrigem.setPaintLabels(true);
        sliOrigem.setPaintTicks(true);
        sliOrigem.setValue(25);
        sliOrigem.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sliOrigemMouseDragged(evt);
            }
        });

        botReiniciar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        botReiniciar.setForeground(new java.awt.Color(51, 51, 51));
        botReiniciar.setText("Reiniciar");
        botReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botReiniciarActionPerformed(evt);
            }
        });

        botSair.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        botSair.setForeground(new java.awt.Color(51, 51, 51));
        botSair.setText("Sair");
        botSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSairActionPerformed(evt);
            }
        });

        pOrigem.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "De:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        pOrigem.setForeground(new java.awt.Color(51, 51, 51));
        pOrigem.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        grupoOrigem.add(rbCelsiusO);
        rbCelsiusO.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        rbCelsiusO.setSelected(true);
        rbCelsiusO.setText("Celsius");
        rbCelsiusO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCelsiusOActionPerformed(evt);
            }
        });

        grupoOrigem.add(rbKelvinO);
        rbKelvinO.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        rbKelvinO.setText(" Kelvin");
        rbKelvinO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbKelvinOActionPerformed(evt);
            }
        });

        grupoOrigem.add(rbFahrO);
        rbFahrO.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        rbFahrO.setText("Fahrenheit");
        rbFahrO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFahrOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pOrigemLayout = new javax.swing.GroupLayout(pOrigem);
        pOrigem.setLayout(pOrigemLayout);
        pOrigemLayout.setHorizontalGroup(
            pOrigemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOrigemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pOrigemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbCelsiusO)
                    .addComponent(rbKelvinO)
                    .addComponent(rbFahrO))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pOrigemLayout.setVerticalGroup(
            pOrigemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOrigemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbCelsiusO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbKelvinO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbFahrO)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pDestino.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Para:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        pDestino.setForeground(new java.awt.Color(51, 51, 51));

        grupoDestino.add(rbCelsiusD);
        rbCelsiusD.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        rbCelsiusD.setText("Celsius");
        rbCelsiusD.setEnabled(false);

        grupoDestino.add(rbKelvinD);
        rbKelvinD.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        rbKelvinD.setSelected(true);
        rbKelvinD.setText(" Kelvin");
        rbKelvinD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbKelvinDActionPerformed(evt);
            }
        });

        grupoDestino.add(rbFahrD);
        rbFahrD.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        rbFahrD.setText("Fahrenheit");
        rbFahrD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFahrDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pDestinoLayout = new javax.swing.GroupLayout(pDestino);
        pDestino.setLayout(pDestinoLayout);
        pDestinoLayout.setHorizontalGroup(
            pDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDestinoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbCelsiusD)
                    .addComponent(rbKelvinD)
                    .addComponent(rbFahrD))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pDestinoLayout.setVerticalGroup(
            pDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDestinoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbCelsiusD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbKelvinD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbFahrD)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        lConversao.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lConversao.setForeground(new java.awt.Color(51, 51, 51));
        lConversao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lConversao.setText("298");
        lConversao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        lOrigem.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lOrigem.setForeground(new java.awt.Color(51, 51, 51));
        lOrigem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lOrigem.setText("25");
        lOrigem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sliOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lConversao, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botReiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sliOrigem, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(lOrigem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(botSair)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botReiniciar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pOrigem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pDestino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(lConversao, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, 65))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botSairActionPerformed

    private void rbKelvinOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbKelvinOActionPerformed
        int valor = sliOrigem.getValue();
        int maxAtual = sliOrigem.getMaximum();
        int novoValor;
        
        if(maxAtual == 100){ 
            novoValor = celsiusParaKelvin(valor);
            rbCelsiusD.setEnabled(true);
            rbCelsiusD.setSelected(true);
        }else{
            novoValor = fahrenheitParaKelvin(valor);
            rbFahrD.setEnabled(true);
            rbFahrD.setSelected(true);
        }   
        rbKelvinD.setEnabled(false);
        
        
        sliOrigem.setMaximum(373);
        sliOrigem.setMinimum(273);
        
        
        sliOrigem.setValue(novoValor);
        String texto = String.valueOf(novoValor);
        lOrigem.setText(texto);
        
        String textoConv = String.valueOf(valor);
        lConversao.setText(textoConv);
    }//GEN-LAST:event_rbKelvinOActionPerformed

    private void rbFahrOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFahrOActionPerformed
        int valor = sliOrigem.getValue();
        int maxAtual = sliOrigem.getMaximum();
        int novoValor;
        
        if(maxAtual == 100){ 
            novoValor = celsiusParaFahrenheit(valor);
            rbCelsiusD.setEnabled(true);
            rbCelsiusD.setSelected(true);
        }else{
            novoValor = kelvinParaFahrenheit(valor);
            rbKelvinD.setEnabled(true);
            rbKelvinD.setEnabled(true);
        }   
        rbFahrD.setEnabled(false);
        
        sliOrigem.setMaximum(212);
        sliOrigem.setMinimum(32);
        
        
        sliOrigem.setValue(novoValor);
        String texto = String.valueOf(novoValor);
        lOrigem.setText(texto);
        
        String textoConv = String.valueOf(valor);
        lConversao.setText(textoConv);
    }//GEN-LAST:event_rbFahrOActionPerformed

    private void rbKelvinDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbKelvinDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbKelvinDActionPerformed

    private void rbFahrDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFahrDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFahrDActionPerformed

    private void sliOrigemMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliOrigemMouseDragged
        rbCelsiusO.setSelected(true);
        int valor = sliOrigem.getValue();
        String texto = String.valueOf(valor);
        lOrigem.setText(texto);
        
        int valorConv;
        if(rbCelsiusO.isSelected() ){
            if(rbKelvinD.isSelected() ){
                valorConv = celsiusParaKelvin(valor);
            }else{
                valorConv = celsiusParaFahrenheit(valor);
            }
        }else{
            if(rbKelvinO.isSelected() ){
                if(rbCelsiusD.isSelected() ){
                    valorConv = kelvinParaCelsius(valor);
                }else{
                    valorConv = kelvinParaFahrenheit(valor);
                }   
            }else{
                if(rbCelsiusD.isSelected() ){ 
                    valorConv = fahrenheitParaCelsius(valor);
                }else{
                    valorConv = fahrenheitParaKelvin(valor);
                }
            }
        }
        String textoConv = String.valueOf(valorConv);
        lConversao.setText(textoConv);
    }//GEN-LAST:event_sliOrigemMouseDragged

    private void rbCelsiusOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCelsiusOActionPerformed
        int valor = sliOrigem.getValue();
        int maxAtual = sliOrigem.getMaximum();
        int novoValor;
        
        if(maxAtual == 373){ 
            novoValor = kelvinParaCelsius(valor);
            rbKelvinD.setEnabled(true);
            rbKelvinD.setSelected(true);
        }else{
            novoValor = kelvinParaFahrenheit(valor);
            rbFahrD.setEnabled(true);
            rbFahrD.setEnabled(true);
        }   
        rbCelsiusD.setEnabled(false);
        
        sliOrigem.setMaximum(100);
        sliOrigem.setMinimum(0);
        
        
        sliOrigem.setValue(novoValor);
        String texto = String.valueOf(novoValor);
        lOrigem.setText(texto);
        
        String textoConv = String.valueOf(valor);
        lConversao.setText(textoConv);
    }//GEN-LAST:event_rbCelsiusOActionPerformed

    private void botReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botReiniciarActionPerformed
        sliOrigem.setMaximum(100);
        sliOrigem.setMinimum(0);
        sliOrigem.setValue(25);
        
        rbCelsiusO.setSelected(true);
        rbCelsiusD.setEnabled(false);
        
        rbKelvinD.setSelected(true);
        
        int novoValor = sliOrigem.getValue();
        String texto = String.valueOf(novoValor);
        lOrigem.setText(texto);
        
        String text = String.valueOf(celsiusParaKelvin(novoValor));
        lConversao.setText(text);
    }//GEN-LAST:event_botReiniciarActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversaoTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversaoTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversaoTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversaoTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversaoTemperatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botReiniciar;
    private javax.swing.JButton botSair;
    private javax.swing.ButtonGroup grupoDestino;
    private javax.swing.ButtonGroup grupoOrigem;
    private javax.swing.JLabel lConversao;
    private javax.swing.JLabel lOrigem;
    private javax.swing.JPanel pDestino;
    private javax.swing.JPanel pOrigem;
    private javax.swing.JRadioButton rbCelsiusD;
    private javax.swing.JRadioButton rbCelsiusO;
    private javax.swing.JRadioButton rbFahrD;
    private javax.swing.JRadioButton rbFahrO;
    private javax.swing.JRadioButton rbKelvinD;
    private javax.swing.JRadioButton rbKelvinO;
    private javax.swing.JSlider sliOrigem;
    // End of variables declaration//GEN-END:variables
}
